sysInfo: True
netInfo: False
sysStat: True
netStat: False
logfile: "/home/giammp/botnet/log.txt"
targets:
  - url: "http://www.google.com"
    timeMin: 1000
    timeMax: 3000
    maxAttempts: 5
  - url: "http://www.twitter.com"
    timeMin: 2000
    timeMax: 4000
    maxAttempts: 5
  - url: "http://www.facebook.com"
    timeMin: 3000
    timeMax: 5000
    maxAttempts: 5
sleep:
  - condition: "expression1"
  - condition: "expression2"
debug: True