sysInfo: True
netInfo: True
sysStat: True
netStat: True
sysStatTime: 5000
netStatTime: 5000
logfile: "/home/giammp/botnet/log.txt"
cmdfile: "/home/giammp/botnet/cmd.txt"
targets:
  - url: "http://www.google.com"
    period: 1
    maxAttempts: 5
  - url: "http://www.twitter.com"
    period: 2-4
    maxAttempts: 5
proxy:
  address: "http://www.securewebproxy.gq"
  port: 80
sleep:
  - condition: "expression1"
  - condition: "expression2"
debug: True